name: tarotflash
description: "Flash Cards for Learning Tarot"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tarot_images/

flutter_launcher_icons:
  image_path: "assets/icons/icon.png" 
  android: true
  ios: true