class TarotModel {
  final String key;
  final String name;
  final String meaning;
  final String reversedMeaning;
  final String imageName;
  final String group;

  static final List<TarotModel> all = [
    TarotModel(
      key: "the_fool",
      name: "The Fool",
      meaning: "New beginnings, innocence, spontaneity, adventure",
      reversedMeaning: "Recklessness, foolishness, lack of direction",
      imageName: "assets/tarot_images/1_the_fool.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_magician",
      name: "The Magician",
      meaning: "Manifestation, resourcefulness, power",
      reversedMeaning: "Manipulation, poor planning, untapped talents",
      imageName: "assets/tarot_images/2_the_magician.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_high_priestess",
      name: "The High Priestess",
      meaning: "Intuition, mystery, subconscious mind",
      reversedMeaning: "Secrets, disconnected from intuition, withdrawal",
      imageName: "assets/tarot_images/3_the_high_priestess.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "The Empress",
      name: "The Empress",
      meaning: "Fertility, abundance, nurturing",
      reversedMeaning: "Dependence, smothering, creative block",
      imageName: "assets/tarot_images/4_the_empress.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_emperor",
      name: "The Emperor",
      meaning: "Authority, structure, control",
      reversedMeaning: "Domination, rigidity, inflexibility",
      imageName: "assets/tarot_images/5_the_emperor.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_hierophant",
      name: "The Hierophant",
      meaning: "Tradition, conformity, spiritual guidance",
      reversedMeaning: "Rebellion, subversiveness, new approaches",
      imageName: "assets/tarot_images/6_the_hierophant.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_loversd",
      name: "The Lovers",
      meaning: "Love, relationships, choices",
      reversedMeaning: "Disharmony, imbalance, misalignment of values",
      imageName: "assets/tarot_images/7_the_lovers.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_chariot",
      name: "The Chariot",
      meaning: "Determination, control, victory",
      reversedMeaning: "Lack of control, aggression, obstacles",
      imageName: "assets/tarot_images/8_the_chariot.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "strength",
      name: "Strength",
      meaning: "Courage, compassion, inner strength",
      reversedMeaning: "Self-doubt, weakness, insecurity",
      imageName: "assets/tarot_images/9_strength.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_hermit",
      name: "The Hermit",
      meaning: "Introspection, solitude, guidance",
      reversedMeaning: "Isolation, loneliness, withdrawal",
      imageName: "assets/tarot_images/10_the_hermit.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "wheel_of_fortune",
      name: "Wheel of Fortune",
      meaning: "Change, cycles, fate",
      reversedMeaning: "Bad luck, resistance to change, breaking cycles",
      imageName: "assets/tarot_images/11_wheel_of_fortune.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "justice",
      name: "Justice",
      meaning: "Fairness, truth, law",
      reversedMeaning: "Dishonesty, lack of accountability, unfairness",
      imageName: "assets/tarot_images/12_justice.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_hanged_man",
      name: "The Hanged Man",
      meaning: "Surrender, new perspective, suspension",
      reversedMeaning: "Delays, resistance, stalling",
      imageName: "assets/tarot_images/13_the_hanged_man.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "death",
      name: "Death",
      meaning: "Transformation, endings, change",
      reversedMeaning: "Resistance to change, personal transformation, inner purging",
      imageName: "assets/tarot_images/14_death.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "temperance",
      name: "Temperance",
      meaning: "Balance, moderation, patience",
      reversedMeaning: "Imbalance, excess, lack of long-term vision",
      imageName: "assets/tarot_images/15_temperance.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_devil",
      name: "The Devil",
      meaning: "Bondage, addiction, materialism",
      reversedMeaning: "Detachment, freedom, release",
      imageName: "assets/tarot_images/16_the_devil.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_tower",
      name: "The Tower",
      meaning: "Sudden upheaval, disaster, revelation",
      reversedMeaning: "Avoidance of disaster, fear of change, resistance",
      imageName: "assets/tarot_images/17_the_tower.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_star",
      name: "The Star",
      meaning: "Hope, faith, rejuvenation",
      reversedMeaning: "Lack of faith, despair, discouragement",
      imageName: "assets/tarot_images/18_the_star.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_moon",
      name: "The Moon",
      meaning: "Illusion, fear, anxiety",
      reversedMeaning: "Clarity, truth, overcoming fear",
      imageName: "assets/tarot_images/19_the_moon.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_sun",
      name: "The Sun",
      meaning: "Joy, success, positivity",
      reversedMeaning: "Temporary depression, lack of success, pessimism",
      imageName: "assets/tarot_images/20_the_sun.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "judgement",
      name: "Judgement",
      meaning: "Rebirth, inner calling, absolution",
      reversedMeaning: "Self-doubt, refusal of self-examination, stagnation",
      imageName: "assets/tarot_images/21_judgement.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "the_world",
      name: "The World",
      meaning: "Completion, accomplishment, travel",
      reversedMeaning: "Lack of closure, incompletion, shortcuts",
      imageName: "assets/tarot_images/22_the_world.svg",
      group: "Major Arcana",
    ),
    TarotModel(
      key: "ace_of_wands",
      name: "Ace of Wands",
      meaning: "Inspiration, new opportunities, growth",
      reversedMeaning: "Delays, lack of motivation, missed opportunities",
      imageName: "assets/tarot_images/37_ace_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "two_of_wands",
      name: "Two of Wands",
      meaning: "Planning, decisions, discovery",
      reversedMeaning: "Fear of change, indecisiveness, lack of planning",
      imageName: "assets/tarot_images/38_two_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "three_of_wands",
      name: "Three of Wands",
      meaning: "Progress, foresight, expansion",
      reversedMeaning: "Delays, lack of foresight, obstacles to long-term goals",
      imageName: "assets/tarot_images/39_three_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "four_of_wands",
      name: "Four of Wands",
      meaning: "Celebration, harmony, homecoming",
      reversedMeaning: "Lack of communication, instability, home conflicts",
      imageName: "assets/tarot_images/40_four_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "five_of_wands",
      name: "Five of Wands",
      meaning: "Conflict, competition, tension",
      reversedMeaning: "Avoiding conflict, respecting differences, resolving conflicts",
      imageName: "assets/tarot_images/41_five_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "six_of_wands",
      name: "Six of Wands",
      meaning: "Victory, recognition, success",
      reversedMeaning: "Egotism, fall from grace, lack of recognition",
      imageName: "assets/tarot_images/42_six_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "seven_of_wands",
      name: "Seven of Wands",
      meaning: "Perseverance, defense, maintaining control",
      reversedMeaning: "Giving up, overwhelmed, lack of confidence",
      imageName: "assets/tarot_images/43_seven_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "eight_of_wands",
      name: "Eight of Wands",
      meaning: "Swift action, movement, communication",
      reversedMeaning: "Delays, frustration, missed messages",
      imageName: "assets/tarot_images/44_eight_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "nine_of_wands",
      name: "Nine of Wands",
      meaning: "Resilience, persistence, courage",
      reversedMeaning: "Exhaustion, stubbornness, defensiveness",
      imageName: "assets/tarot_images/45_nine_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "ten_of_wands",
      name: "Ten of Wands",
      meaning: "Burden, responsibility, hard work",
      reversedMeaning: "Taking on too much, avoiding responsibility, release of burden",
      imageName: "assets/tarot_images/46_ten_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "page_of_wands",
      name: "Page of Wands",
      meaning: "Enthusiasm, exploration, discovery",
      reversedMeaning: "Lack of direction, procrastination, creating conflict",
      imageName: "assets/tarot_images/47_page_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "knight_of_wands",
      name: "Knight of Wands",
      meaning: "Energy, passion, adventure",
      reversedMeaning: "Recklessness, haste, scattered energy",
      imageName: "assets/tarot_images/48_knight_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "queen_of_wands",
      name: "Queen of Wands",
      meaning: "Confidence, independence, determination",
      reversedMeaning: "Selfishness, jealousy, insecurity",
      imageName: "assets/tarot_images/49_queen_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "king_of_wands",
      name: "King of Wands",
      meaning: "Leadership, vision, entrepreneurial spirit",
      reversedMeaning: "Impulsiveness, ruthlessness, high expectations",
      imageName: "assets/tarot_images/50_king_of_wands.svg",
      group: "Wands",
    ),
    TarotModel(
      key: "ace_of_cups",
      name: "Ace of Cups",
      meaning: "Love, compassion, creativity",
      reversedMeaning: "Emotional loss, blocked creativity, emptiness",
      imageName: "assets/tarot_images/51_ace_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "two_of_cups",
      name: "Two of Cups",
      meaning: "Partnership, unity, love",
      reversedMeaning: "Breakup, imbalance, lack of harmony",
      imageName: "assets/tarot_images/52_two_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "three_of_cups",
      name: "Three of Cups",
      meaning: "Celebration, friendship, community",
      reversedMeaning: "Overindulgence, gossip, isolation",
      imageName: "assets/tarot_images/53_three_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "four_of_cups",
      name: "Four of Cups",
      meaning: "Apathy, contemplation, disconnection",
      reversedMeaning: "Awareness, acceptance, choosing happiness",
      imageName: "assets/tarot_images/54_four_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "five_of_cups",
      name: "Five of Cups",
      meaning: "Loss, regret, disappointment",
      reversedMeaning: "Moving on, forgiveness, hope returning",
      imageName: "assets/tarot_images/55_five_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "six_of_cups",
      name: "Six of Cups",
      meaning: "Nostalgia, childhood, memories",
      reversedMeaning: "Stuck in the past, naivety, unrealistic expectations",
      imageName: "assets/tarot_images/56_six_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "seven_of_cups",
      name: "Seven of Cups",
      meaning: "Choices, imagination, illusion",
      reversedMeaning: "Clarity, reality, making informed choices",
      imageName: "assets/tarot_images/57_seven_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "eight_of_cups",
      name: "Eight of Cups",
      meaning: "Abandonment, withdrawal, moving on",
      reversedMeaning: "Fear of change, avoidance, hopelessness",
      imageName: "assets/tarot_images/58_eight_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "nine_of_cups",
      name: "Nine of Cups",
      meaning: "Contentment, satisfaction, gratitude",
      reversedMeaning: "Greed, dissatisfaction, materialism",
      imageName: "assets/tarot_images/59_nine_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "ten_of_cups",
      name: "Ten of Cups",
      meaning: "Happiness, fulfillment, emotional contentment",
      reversedMeaning: "Broken relationships, disconnection, domestic disharmony",
      imageName: "assets/tarot_images/60_ten_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "page_of_cups",
      name: "Page of Cups",
      meaning: "Creativity, intuition, new emotional experiences",
      reversedMeaning: "Emotional immaturity, insecurity, creative block",
      imageName: "assets/tarot_images/61_page_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "knight_of_cups",
      name: "Knight of Cups",
      meaning: "Romance, charm, imagination",
      reversedMeaning: "Unrealistic expectations, moodiness, jealousy",
      imageName: "assets/tarot_images/62_knight_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "queen_of_cups",
      name: "Queen of Cups",
      meaning: "Compassion, nurturing, emotional security",
      reversedMeaning: "Emotional insecurity, co-dependency, over-sensitivity",
      imageName: "assets/tarot_images/63_queen_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "king_of_cups",
      name: "King of Cups",
      meaning: "Emotional balance, control, generosity",
      reversedMeaning: "Emotional manipulation, moodiness, volatility",
      imageName: "assets/tarot_images/64_king_of_cups.svg",
      group: "Cups",
    ),
    TarotModel(
      key: "ace_of_swords",
      name: "Ace of Swords",
      meaning: "Clarity, new ideas, breakthroughs",
      reversedMeaning: "Confusion, brutality, miscommunication",
      imageName: "assets/tarot_images/65_ace_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "two_of_swords",
      name: "Two of Swords",
      meaning: " Indecision, stalemate, choices",
      reversedMeaning: "Lesser of two evils, no right choice, confusion",
      imageName: "assets/tarot_images/66_two_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "three_of_swords",
      name: "Three of Swords",
      meaning: "Heartbreak, sorrow, grief",
      reversedMeaning: "Recovery, forgiveness, moving on",
      imageName: "assets/tarot_images/67_three_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "four_of_swords",
      name: "Four of Swords",
      meaning: "Rest, recuperation, contemplation",
      reversedMeaning: "Restlessness, burnout, stress",
      imageName: "assets/tarot_images/68_four_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "five_of_swords",
      name: "Five of Swords",
      meaning: "Conflict, defeat, betrayal",
      reversedMeaning: "Reconciliation, making amends, past resentment",
      imageName: "assets/tarot_images/69_five_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "six_of_swords",
      name: "Six of Swords",
      meaning: "Transition, moving on, travel",
      reversedMeaning: "Stuck in the past, unable to move on, carrying baggage",
      imageName: "assets/tarot_images/70_six_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "seven_of_swords",
      name: "Seven of Swords",
      meaning: "Deception, strategy, trickery",
      reversedMeaning: "Coming clean, rethinking approach, deceit exposed",
      imageName: "assets/tarot_images/71_seven_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "eight_of_swords",
      name: "Eight of Swords",
      meaning: "Restriction, imprisonment, fear",
      reversedMeaning: "Freedom, self-acceptance, new perspectives",
      imageName: "assets/tarot_images/72_eight_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "nine_of_swords",
      name: "Nine of Swords",
      meaning: "Anxiety, despair, nightmares",
      reversedMeaning: "Hope, reaching out for help, recovery",
      imageName: "assets/tarot_images/73_nine_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "ten_of_swords",
      name: "Ten of Swords",
      meaning: "Ruin, failure, betrayal",
      reversedMeaning: "Recovery, regeneration, inevitable end",
      imageName: "assets/tarot_images/74_ten_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "page_of_swords",
      name: "Page of Swords",
      meaning: "Curiosity, communication, new ideas",
      reversedMeaning: "Gossip, deceit, all talk and no action",
      imageName: "assets/tarot_images/75_page_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "knight_of_swords",
      name: "Knight of Swords",
      meaning: "Ambition, action, drive",
      reversedMeaning: "Impulsiveness, recklessness, unfocused energy",
      imageName: "assets/tarot_images/76_knight_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "queen_of_swords",
      name: "Queen of Swords",
      meaning: "Independence, perception, clarity",
      reversedMeaning: "Cold-heartedness, cruelty, bitterness",
      imageName: "assets/tarot_images/77_queen_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "king_of_swords",
      name: "King of Swords",
      meaning: "Authority, truth, intellectual power",
      reversedMeaning: "Manipulative, tyrannical, abusive",
      imageName: "assets/tarot_images/78_king_of_swords.svg",
      group: "Swords",
    ),
    TarotModel(
      key: "ace_of_pentacles",
      name: "Ace of Pentacles",
      meaning: "Opportunity, prosperity, new ventures",
      reversedMeaning: "Lost opportunity, lack of planning, greed",
      imageName: "assets/tarot_images/23_ace_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "two_of_pentacles",
      name: "Two of Pentacles",
      meaning: "Balance, adaptability, multitasking",
      reversedMeaning: "Overwhelmed, lack of balance, disorganization",
      imageName: "assets/tarot_images/24_two_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "three_of_pentacles",
      name: "Three of Pentacles",
      meaning: "Collaboration, skill, teamwork",
      reversedMeaning: "Lack of teamwork, poor workmanship, misalignment",
      imageName: "assets/tarot_images/25_three_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "four_of_pentacles",
      name: "Four of Pentacles",
      meaning: "Control, stability, possessiveness",
      reversedMeaning: "Greed, materialism, letting go",
      imageName: "assets/tarot_images/26_four_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "five_of_pentacles",
      name: "Five of Pentacles",
      meaning: "Hardship, loss, isolation",
      reversedMeaning: "Recovery, improvement, end of hardship",
      imageName: "assets/tarot_images/27_five_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "six_of_pentacles",
      name: "Six of Pentacles",
      meaning: "Generosity, charity, sharing",
      reversedMeaning: "Selfishness, debt, one-sided charity",
      imageName: "assets/tarot_images/28_six_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "seven_of_pentacles",
      name: " of Pentacles",
      meaning: "Patience, investment, assessment",
      reversedMeaning: "Lack of reward, impatience, lack of long-term vision",
      imageName: "assets/tarot_images/29_seven_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "eight_of_pentacles",
      name: "Eight of Pentacles",
      meaning: "Diligence, craftsmanship, mastery",
      reversedMeaning: "Lost opportunity, lack of planning, greed",
      imageName: "assets/tarot_images/30_eight_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "nine_of_pentacles",
      name: "Nine of Pentacles",
      meaning: "Luxury, self-sufficiency, financial gain",
      reversedMeaning: "Overindulgence, financial setbacks, dependence",
      imageName: "assets/tarot_images/31_nine_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "ten_of_pentacles",
      name: "Ten of Pentacles",
      meaning: "Legacy, inheritance, culmination",
      reversedMeaning: "Financial failure, loss, lack of stability",
      imageName: "assets/tarot_images/32_ten_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "page_of_pentacles",
      name: "Page of Pentacles",
      meaning: "Manifestation, new opportunities, study",
      reversedMeaning: "Lack of progress, short-term focus, daydreaming",
      imageName: "assets/tarot_images/33_page_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "knight_of_pentacles",
      name: "knight of Pentacles",
      meaning: "Efficiency, hard work, responsibility",
      reversedMeaning: "Laziness, routine, conservatism",
      imageName: "assets/tarot_images/34_knight_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "queen_of_pentacles",
      name: "Queen of Pentacles",
      meaning: "Nurturing, practicality, security",
      reversedMeaning: "Self-centeredness, work-home imbalance, smothering",
      imageName: "assets/tarot_images/35_queen_of_pentacles.svg",
      group: "Pentacles",
    ),
    TarotModel(
      key: "king_of_pentacles",
      name: "King of Pentacles",
      meaning: "Wealth, business, discipline",
      reversedMeaning: "Greed, indulgence, stubbornness",
      imageName: "assets/tarot_images/36_king_of_pentacles.svg",
      group: "Pentacles",
    ),
  ];

  TarotModel({
    required this.key,
    required this.name,
    required this.meaning,
    required this.reversedMeaning,
    required this.imageName,
    required this.group,
  });
}
